# **Chapter 1: Python Basics:**

## 1. Exercise : **Your first Python code**
It's time to run your first Python code!

Head to the code and hit the run code button to see the output.

**Instructions**<br>
- Hit the run code button to see the output of print(5 / 8)

In [1]:
# Hit run code to see the output!
print(5 / 8)

0.625


## 2. Exercise : **Python as a calculator**<br>
Python is perfectly suited to do basic calculations. It can do addition, subtraction, multiplication and division.

The code in the script gives some examples.


**Instructions**<br>
- Print the sum of 4 + 5.<br>
- Print the result of subtracting 5 from 5.<br>
- Print the result of multiplying 3 by 5.<br>
- Print the result of dividing 10 by 2.

In [2]:
# Addition
print(4+5)

# Subtraction
print(5 - 5)

# Multiplication
print(3 * 5)

# Division
print(10 / 2)

9
0
15
5.0


## 3. Exercise : **Variable Assignment**<br>
In Python, a variable allows you to refer to a value with a name. To create a variable x with a value of 5, you use =, like this example:

x = 5<br>
You can now use the name of this variable, x, instead of the actual value, 5.

Remember, = in Python means assignment, it doesn't test equality! Try it in the exercise by replacing ____ with your code.

**Instructions**<br>
- Create a variable savings with the value of 100.<br>
- Check out this variable by typing print(savings) in the script

In [3]:
# Create a variable savings
savings = 100

# Print out savings
print(savings)

100


## 4. Exercise : **Calculations with variables**<br>
You've now created a savings variable, so let's start saving!

Instead of calculating with the actual values, you can use variables instead.

How much money would you have saved four months from now, if you saved $10 each month?

**Instructions**<br>
- Create a variable monthly_savings, equal to 10 and num_months, equal to 4.<br>
- Multiply monthly_savings by num_months and assign it to new_savings.<br>
- Print the value of new_savings.

In [4]:
# Create the variables monthly_savings and num_months
monthly_savings = 10
num_months = 4

# Multiply monthly_savings and num_months
new_savings = monthly_savings * num_months

# Print new_savings
print(new_savings)

40


## 5. Exercise : **Other variable types**<br>

In the previous exercise, you worked with the integer Python data type:

`int, or integer`: a number without a fractional part. savings, with the value 100, is an example of an integer.
Next to numerical data types, there are three other very common data types:

`float, or floating point`: a number that has both an integer and fractional part, separated by a point. 1.1, is an example of a float.<br>
`str, or string`: a type to represent text. You can use single or double quotes to build a string.<br>
`bool, or boolean`: a type to represent logical values. It can only be True or False (the capitalization is important!).


**Instructions**<br>
- Create a new float, half, with the value 0.5.<br>
- Create a new string, intro, with the value "Hello! How are you?".<br>
- Create a new boolean, is_good, with the value True.<br>

In [5]:
# Create a variable half
half = 0.5

# Create a variable intro
intro = "Hello! How are you?"

# Create a variable is_good
is_good = True

## 6. Exercise :**Operations with other types**<br>
Variables come in different types in Python. You can see the type of a variable by using `type()`. For example, to see type of a, execute: type(a).

Different types behave differently in Python. When you sum two strings, for example, you'll get different behavior than when you sum two integers or two booleans.

Time for you to test this out.

**Instructions** <br>

- Add savings and new_savings and assign it to total_savings.<br>
- Use type() to print the resulting type of total_savings.<br>
- Calculate the sum of intro and intro and assign the result to doubleintro.<br>
- Print out doubleintro. Did you expect this?

In [6]:
savings = 100
new_savings = 40

# Calculate total_savings using savings and new_savings
total_savings = savings + new_savings
print(total_savings)

# Print the type of total_savings
print(type(total_savings))

140
<class 'int'>


In [7]:
intro = "Hello! How are you?"

# Assign sum of intro and intro to doubleintro
doubleintro = intro + intro

# Print out doubleintro
print(doubleintro)

Hello! How are you?Hello! How are you?


# **Chapter 2: Python Lists:**

## 1. Exercise: Create a list
A list is a compound data type; you can group values together, like this:

`a = "is"
b = "nice"
my_list = ["my", "list", a, b]`
After measuring the height of your family, you decide to collect some information on the house you're living in. The areas of the different parts of your house are stored in separate variables in the exercise.

**Instructions**
- Create a list, areas, that contains the area of the hallway (hall), kitchen (kit), living room (liv), bedroom (bed) and bathroom (bath), in this order. Use the predefined variables.
- Print areas with the print() function.

In [18]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


## 2. Exercise: Create lists with different types
Although it's not really common, a `list can also contain a mix of Python types` including `strings, floats, and booleans`.

You're now going to add the room names to your list, so you can easily see both the room name and size together.

Some of the code has been provided for you to get you started. Pay attention here! "bathroom" is a string, while bath is a variable that represents the float 9.50 you specified earlier.

**Instructions**
- Finish the code that creates the areas list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings "hallway", "kitchen" and "bedroom" at the appropriate locations.
- Print areas again; is the printout more informative this time?

In [19]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


## 3. Exercise: List of lists
As a data scientist, you'll often be dealing with a lot of data, and it will make sense to group some of this data.

Instead of creating a list containing strings and floats, representing the names and areas of the rooms in your house, you can create a list of lists.

Remember: `"hallway" is a string`, while hall is a variable that represents the float 11.25 you specified earlier.

**Instructions**
- Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!
- Print out house; does this way of structuring your data make more sense?

In [20]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# House information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
        ["bedroom", bed],
        ["bathroom", bath]]

# Print out house
print(house)

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]


## 4. Exercise : Subset and conquer
Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list x and then selects "b" from it. Remember that this is the second element, so it has index 1. You can also use negative indexing.

`x = ["a", "b", "c", "d"]
x[1]
x[-3]` # same result!
Remember the areas list from before, containing both strings and floats? Its definition is already in the script. Can you add the correct code to do some Python subsetting?

**Instructions**
- Print out the second element from the areas list (it has the value 11.25).
- Subset and print out the last element of areas, being 9.50. Using a negative index makes sense here!
- Select the number representing the area of the living room (20.0) and print it out.

In [21]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


## 5. Exercise: Slicing and dicing
Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

`my_list[start:end]`
`The start index will be included, while the end index is not`. However, it's also possible not to specify these indexes. If you don't specify the start index, Python figures out that you want to start your slice at the beginning of your list.

**Instructions**
- Use slicing to create a list, downstairs, that contains the first 6 elements of areas.
- Create upstairs, as the last 4 elements of areas. This time, simplify the slicing by omitting the end index.
- Print both downstairs and upstairs using print().

In [22]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


## 6. Exercise: Subsetting lists of lists
`A Python list can also contain other lists.`

To subset lists of lists, you can use the same technique as before: square brackets. This would look something like this for a list, house:
`house[2][0]`

**Instructions**
- Subset the house list to get the float 9.5.

In [23]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

# Subset the house list
house[4][1]

9.5

## 7. Exercise: Replace list elements
To replace list elements, you subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

For this and the following exercises, you'll continue working on the areas list that contains the names and areas of different rooms in a house.

**Instructions**
- Update the area of the bathroom to be 10.50 square meters instead of 9.50 using negative indexing.
- Make the areas list more trendy! Change "living room" to "chill zone". Don't use negative indexing this time.

In [24]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas [4] = "chill zone"

## 8. Exercise: Extend a list
If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the + operator:

`x = ["a", "b", "c", "d"]
y = x + ["e", "f"]`
You just won the lottery, awesome! You decide to build a poolhouse and a garage. Can you add the information to the areas list?

**Instructions**
- Use the + operator to paste the list` ["poolhouse", 24.5]` to the end of the areas list. Store the resulting list as areas_1.
- Further extend areas_1 by adding data on your garage. Add the string "garage" and float 15.45. Name the resulting list areas_2

In [25]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

## 9. Exercise: Delete list elements
Finally, you can also remove elements from your list. You can do this with the del statement:

`x = ["a", "b", "c", "d"]
del x[1]`

Pay attention here: `as soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change!`

Unfortunately, the amount you won with the lottery is not that big after all and it looks like the poolhouse isn't going to happen. You'll need to remove it from the list. You decide to remove the corresponding string and float from the areas list.

**Instructions**
- Delete the string and float for the "poolhouse" from your areas list.
- Print the updated areas list.

In [26]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Delete the poolhouse items from the list
del areas[10:12]

# Print the updated list
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


## 10. Exercise: Inner workings of lists
Some code has been provided for you in this exercise: a list with the name areas and a copy named `areas_copy`.

Currently, the first element in the areas_copy list is changed and the areas list is printed out. If you hit the run code button you'll see that, although you've changed areas_copy, the change also takes effect in the areas list. That's because areas and areas_copy point to the same list.

If you want to prevent changes in areas_copy from also taking effect in areas, you'll have to do a more explicit copy of the areas list with `list() or by using [:]`.

**Instructions**
- Change the second command, that creates the variable areas_copy, such that areas_copy is an explicit copy of areas. After your edit, changes made to areas_copy shouldn't affect areas. Submit the answer to check this.

In [27]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Change this command
areas_copy = areas[:]

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


# **Chapter 3: Functions and Packages:**

## 1. Exercise: Familiar functions
Out of the box, Python offers a bunch of built-in functions to make your life as a data scientist easier. You already know two such functions: `print() and type()`. There are also functions like `str(), int(), bool() and float(`) to switch between data types. You can find out about them here. These are built-in functions as well.

Calling a function is easy. To get the type of 3.0 and store the output as a new variable, result, you can use the following:

`result = type(3.0)`

**Instructions**
- Use `print()` in combination with `type()` to print out the type of var1.
- Use `len()` to get the length of the list var1. Wrap it in a print() call to directly print it out.
- Use `int() `to convert var2 to an integer. Store the output as out2.

In [28]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


## 2. Exercise: Multiple arguments
In the previous exercise, you identified optional arguments by viewing the documentation with `help()`. You'll now apply this to change the behavior of the `sorted()` function.

Have a look at the documentation of `sorted()` by typing `help(sorted)` in the IPython Shell.

You'll see that `sorted() takes three arguments: iterable, key, and reverse`. In this exercise, you'll only have to specify iterable and reverse, not key.

Two lists have been created for you.

Can you paste them together and sort them in descending order?

**Instructions**
- Use + to merge the contents of first and second into a new list: full.
- Call sorted() and on full and specify the reverse argument to be True. Save the sorted list as full_sorted.
- Finish off by printing out full_sorted.

In [29]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full ,  reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


## 3. Exercise: String Methods
Strings come with a bunch of methods. Follow the instructions closely to discover some of them. If you want to discover them in more detail, you can always type `help(str)` in the IPython Shell.

A string place has already been created for you to experiment with.

**Instructions**
- Use the `.upper() `method on place and store the result in place_up. Use the syntax for calling methods that you learned in the previous video.
- Print out place and place_up. Did both change?
- Print out the number of o's on the variable place by calling `.count()` on place and passing the letter 'o' as an input to the method. We're talking about the variable place, not the word "place"!

In [30]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place
place_up = place.upper()

# Print out place and place_up
print(place, place_up)


# Print out the number of o's in place
print(place.count("o"))

poolhouse POOLHOUSE
3


## 4. Exercise :**List Methods**<br>
Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:

`.index()`, to get the index of the first element of a list that matches its input and
`.count()`, to get the number of times an element appears in a list.
You'll be working on the list with the area of different parts of a house: areas.

**Instructions**<br>
- Use the .index() method to get the index of the element in areas that is equal to 20.0. Print out this index.<br>
- Call .count() on areas to find out how many times 9.50 appears in the list. Again, simply print out this number.

In [8]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


## 5. Exercise :**List Methods (2)**<br>
Most list methods will change the list they're called on. Examples are:

`.append()`, that adds an element to the list it is called on,
`.remove()`, that removes the first element of a list that matches the input, and
`.reverse()`, that reverses the order of the elements in the list it is called on.
You'll be working on the list with the area of different parts of the house: areas.

**Instructions**<br>
- Use `.append() `twice to add the size of the poolhouse and the garage again: 24.5 and 15.45, respectively. Make sure to add them in this order.<br>
- Print out areas<br>
- Use the `.reverse()` method to reverse the order of the elements in areas.<br>
- Print out areas once more.

In [9]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)


# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


## 6. Exercise : **Import package**<br>
Let's say you wanted to calculate the circumference and area of a circle. Here's what those formulas look like:


Rather than typing the number for pi, you can use the math package that contains the number

For reference, ** is the symbol for exponentiation. For example 3**4 is 3 to the power of 4 and will give 81.

**Instructions**<br>
- Import the math package.<br>
- Use math.pi to calculate the circumference of the circle and store it in C.<br>
- Use math.pi to calculate the area of the circle and store it in A.<br>

In [10]:
# Import the math package
import math

# Calculate C
C = 2 * 0.43 * math.pi

# Calculate A
A = math.pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


## 7. Exercise : **Selective import**<br>
General imports, like import math, make all functionality from the math package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective:

`from math import pi`
Try the same thing again, but this time only use pi.

**Instructions**
- Perform a selective import from the math package where you only import the pi function.
- Use math.pi to calculate the circumference of the circle and store it in C.
- Use math.pi to calculate the area of the circle and store it in A

In [11]:
# Import pi function of math package
from math import pi

# Calculate C
C = 2 * 0.43 * pi

# Calculate A
A = pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


# **Chapter 4: Numpy :**

## 1. Exercise : Your First NumPy Array
You're now going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of numpy, a powerful package to do data science.

A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code to create a numpy array from it?

**Instructions**
- Import the numpy package as np, so that you can refer to numpy with np.
- Use np.array() to create a numpy array from baseball. Name this array np_baseball.
- Print out the type of np_baseball to check that you got it right.

In [12]:
# Import the numpy package as np
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


## 2. Exercise: Baseball players' height
You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: `height_in`. The height is expressed in inches. Can you make a `numpy` array out of it and convert the units to meters?

`height_in` is already available and the numpy package is loaded, so you can start straight away (Source: stat.ucla.edu).

**Instructions**
- Create a numpy array from height_in. Name this new array np_height_in.
- Print `np_height_in`.
- Multiply `np_height_in` with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, `np_height_m`.
- Print out np_height_m and check if the output makes sense.

In [ ]:
# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

## 3. Exercise :Subsetting NumPy Arrays
Subsetting (using the square bracket notation on lists or arrays) works exactly the same with both lists and arrays.

This exercise already has two lists, `height_in` and `weight_lb`, loaded in the background for you. These contain the height and weight of the MLB players as regular lists. It also has two numpy array lists, `np_weight_lb` and `np_height_in` prepared for you.

**Instructions**
- Subset np_weight_lb by printing out the element at index 50.
- Print out a sub-array of np_height_in that contains the elements at index 100 up to and including index 110.

In [ ]:
import numpy as np

np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

## 4. Exercise: Your First 2D NumPy Array
Before working on the actual MLB data, let's try to create a 2D numpy array from a small list of lists.

In this exercise, `baseball` is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already coded for you in the script.

**Instructions**
- Use `np.array()` to create a 2D numpy array from baseball. Name it np_baseball.
- Print out the type of `np_baseball`.
- Print out the shape attribute of np_baseball. Use `np_baseball.shape`.

In [13]:
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
 

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


## 5. Exercise: Baseball data in 2D form
You realize that it makes more sense to restructure all this information in a `2D numpy array`.

You have a Python list of lists. In this list of lists, each sublist represents the height and weight of a single baseball player. The name of this list is baseball and it has been loaded for you already (although you can't see it).

Store the data as a 2D array to unlock numpy's extra functionality.

Instructions
- Use `np.array()` to create a 2D numpy array from baseball. Name it `np_baseball`.
- Print out the shape attribute of np_baseball.

In [14]:
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


## 6. Exercise :Subsetting 2D NumPy Arrays
If your 2D numpy array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements "a" and "c" are extracted from a list of lists.

# numpy
`import numpy as np
np_x = np.array(x)
np_x[:, 0]`
The indexes before the comma refer to the` rows,` while those after the comma refer to the `columns`. The `:` is for `slicing`; in this example, it tells Python to include all rows.

**Instructions**
- Print out the 50th row of np_baseball.
- Make a new variable, np_weight_lb, containing the entire second column of np_baseball.
- Select the height (first column) of the 124th baseball player in np_baseball and print it out.

In [ ]:
import numpy as np

np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[123,0])

## 7. Exercise: 2D Arithmetic
2D numpy arrays can perform calculations element by element, like numpy arrays.

`np_baseball` is coded for you; it's again a 2D numpy array with 3 columns representing `height (in inches), weight (in pounds) and age (in years)`. baseball is available as a regular list of lists and updated is available as 2D numpy array.

**Instructions**
- You managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D numpy array, updated. Add np_baseball and updated and print out the result.
- You want to convert the units of height and weight to metric (meters and kilograms, respectively). As a first step, create a numpy array with three values: 0.0254, 0.453592 and 1. Name this array conversion.
- Multiply np_baseball with conversion and print out the result.

In [ ]:
import numpy as np

np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254,0.453592,1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

## 8. Exercise: Average versus median
You now know how to use numpy functions to get a better feeling for your data.

The `baseball` data is available as a `2D numpy` array with `3 columns (height, weight, age)` and `1015 rows`. The name of this numpy array is `np_baseball`. After restructuring the data, however, you notice that some height values are abnormally high. Follow the instructions and discover which summary statistic is best suited if you're dealing with so-called outliers. np_baseball is available.

**Instructions**
- Create numpy array `np_height_in` that is equal to first column of np_baseball.
- Print out the `mean` of np_height_in.
- Print out the `median` of np_height_in.

In [16]:
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np.array(np_baseball[:,0])

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

198.25
199.0


## 8. Exercise: Explore the baseball data
Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D NumPy array `np_baseball`, with three columns.

The Python script in the editor already includes code to print out informative messages with the different summary statistics and numpy is already loaded as np. Can you finish the job? np_baseball is available.

**Instructions**
- The code to print out the `mean height` is already included. Complete the code for the `median height`. Replace None with the correct code.
- Use `np.std()` on the first column of np_baseball to calculate stddev. Replace None with the correct code.
- Do big players tend to be heavier? Use `np.corrcoef()` to store the correlation between the first and second column of np_baseball in corr. Replace None with the correct code.

In [17]:
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


# **Get coding! Have fun!**